---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: ci-repo
  - name: jvm-consumer-repo

params:

run:
  path: ci-repo/pact-poc-concourse-ci/tasks/publish-pact.sh
