---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "14.04"

inputs:
  - name: code-repository

params:

run:
  path: code-repository/pact-poc-concourse-ci/tasks/publish-pact.sh
