---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: code-repository

params:

run:
  path: code-repository/pact-poc-concourse-ci/tasks/verify-pacts.sh
