---
resources:
  - name: ci-repo
    type: git
    source:
      uri: {{git_uri}}
      branch: {{git_branch}}
      ignore_paths:
        - .gitignore
        - README.md
        - pact-poc-jvm-consumer/src/test/java/*
        - pact-poc-microservice/src/main/java/*
  - name: jvm-consumer-repo
    type: git
    source:
      uri: {{git_uri}}
      branch: {{git_branch}}
      paths:
        - pact-poc-jvm-consumer/src/test/java/*
  - name: microservice-repo
    type: git
    source:
      uri: {{git_uri}}
      branch: {{git_branch}}
      paths:
        - pact-poc-microservice/src/main/java/*

jobs:

  # PUBLISH PACT
  - name: publish-pact
    plan:
      - get: ci-repo
      - get: jvm-consumer-repo
      - task: publish-pact
        file: ci-repo/pact-poc-concourse-ci/tasks/publish-pact.yml

  # VERIFY PACTS
  - name: verify-pacts
    plan:
      - get: ci-repo
      - get: microservice-repo
      - task: verify-pacts
        file: ci-repo/pact-poc-concourse-ci/tasks/verify-pacts.yml
